# Generated by Django 3.0.6 on 2023-06-19 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='office',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='office.Office', verbose_name='Consultorio'),
            preserve_default=False,
        ),
    ]
