# Generated by Django 3.0.6 on 2023-05-29 03:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('paternal_surname', models.CharField(max_length=150, verbose_name='Apellido Paterno')),
                ('maternal_surname', models.CharField(max_length=150, verbose_name='Apellido Materno')),
                ('gender', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=30, verbose_name='Sexo')),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('professional_license', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5,8}$', 'La cedula profesional debe tener entre 5 y 8 digitos.')], verbose_name='Cedula Profesional')),
                ('street', models.CharField(max_length=100, verbose_name='Calle')),
                ('street_number', models.CharField(max_length=15, verbose_name='Numero')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Colonia')),
                ('zip', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'SOLO SE PERMITEN NUMEROS')], verbose_name='Codigo Postal')),
                ('city', models.CharField(max_length=100, verbose_name='Municipio')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('telephone', models.CharField(max_length=13, unique=True, verbose_name='Telefono')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Specialty', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['name'],
            },
        ),
    ]
