# Generated by Django 3.0.6 on 2023-06-20 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20230529_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='curp',
            field=models.CharField(default='1111111111111111', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='El CURP no es válido', regex='^[A-Z]{4}\\d{6}[H,M][A-Z]{5}[A-Z0-9]\\d$')], verbose_name='CURP'),
            preserve_default=False,
        ),
    ]
