# Generated by Django 3.0.6 on 2023-06-20 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_doctor'),
        ('patient', '0003_patient_curp'),
        ('sale', '0004_sale_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name_doctor', models.CharField(blank=True, editable=False, max_length=50)),
                ('name_patient', models.CharField(blank=True, editable=False, max_length=50)),
                ('diagnostic', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.Patient')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.Sale')),
            ],
            options={
                'verbose_name': 'Historial Clinico',
                'verbose_name_plural': 'Historiales Clinicos',
            },
        ),
    ]
