# Generated by Django 3.0.6 on 2023-06-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalhistory',
            name='treatment',
            field=models.CharField(default='tomar', max_length=350),
            preserve_default=False,
        ),
    ]
