# Generated by Django 3.0.6 on 2023-06-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_sale_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='diagnostic',
            field=models.CharField(default='Enfermedad Rara', max_length=50),
            preserve_default=False,
        ),
    ]
