# Generated by Django 3.0.6 on 2023-06-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_sale_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='treatment',
            field=models.CharField(default='Tomar diario', max_length=350),
            preserve_default=False,
        ),
    ]
