# Generated by Django 3.0.6 on 2023-05-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_receptionist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
    ]
